In [13]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import datetime as dt
from matplotlib import font_manager, rc
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score

In [ ]:
# 한글 깨짐 방지 코드
font_name = font_manager.FontProperties(fname="c:/Windows/Fonts/malgun.ttf").get_name()
rc('font', family=font_name)

# 월별

In [18]:
month_data = pd.read_csv('../pre_data/월별_통합_모델링용.csv', index_col=0)
month_data = month_data.drop(columns='date')
month_data

닭고기가격  병아리(원/수)  hot_day  import amount  feedprice     oil_avg     도축  \
0     3202       250        0           8754      533.6  107.066111  58873   
2     3668       420        0          10098      529.9  112.537302  55879   
3     4169       500        0          10836      527.9  117.745606  58750   
4     3399       332        0          13412      526.3  113.723667  60940   
5     3255       200        0          14519      526.2  104.184710  73505   
..     ...       ...      ...            ...        ...         ...    ...   
117   3505       312        3           9360      492.0   69.247955  89892   
118   3074       408        0           9009      503.0   72.975152  81026   
119   3913       447        0          12005      508.0   82.193333  81228   
120   2985       315        0          10025      520.0   79.858712  86819   
121   3320       273        0          11293      511.0   73.308986  90151   

     소_소비자가_int  돼지_소비자가_int  미국기준금리  한국기준금리  
0         59981        18465    0.25    3.25  
2         56019        16634    0.75    3.25  
3         50899        16317    0.25    3.25  
4         53879        15882    0.25    3.25  
5         55403        16798    0.25    3.25  
..          ...          ...     ...     ...  
117       99247        26078    0.25    0.75  
118      103039        26346    0.25    0.75  
119      110791        25977    0.25    0.75  
120      107207        25217    0.25    1.00  
121      108714        27036    0.25    1.00  

[120 rows x 11 columns]

In [19]:
# feature = month_data[['병아리(원/수)', 'hot_day', 'import amount', 'feedprice', 'oil_avg', '도축', '소_소비자가_int', '돼지_소비자가_int', '미국기준금리', '한국기준금리']]
feature = month_data.drop(columns=['닭고기가격'])
target = month_data['닭고기가격']

X_train, X_test, Y_train, y_test = train_test_split(feature, target, test_size=0.3, random_state=2022)

In [20]:
RF_model = RandomForestRegressor()
RF_model.fit(feature,target)

RandomForestRegressor()

In [21]:
n_estimators = 10 
max_features = 4 

RF_reg = RandomForestRegressor(n_estimators=n_estimators, random_state=0, max_features=max_features) 

In [22]:
RF_reg.fit(X_train, Y_train)

RandomForestRegressor(max_features=4, n_estimators=10, random_state=0)

In [23]:
RF_model.score(feature,target)

0.928067387913473

In [25]:
y_pred = RF_reg.predict(X_test)
y_pred

array([3127. , 3098. , 2902.5, 3958.4, 3493.8, 2988.7, 3657.2, 2891.7,
       3071.9, 3828.2, 2995.7, 2847.8, 3365.4, 3300.8, 3411.4, 3146.7,
       2985.8, 3598.2, 3659.4, 3649.9, 2896.9, 3252.2, 3272.4, 3002.8,
       3378.6, 3162.6, 3303.6, 3616.5, 3252.2, 3156.8, 2920.8, 3832.7,
       3665.5, 3306.3, 3519.5, 2902. ])

In [26]:
score_list = cross_val_score(RF_model, feature, target)

In [29]:
print('cross-val-score \n{}'.format(score_list))
print('cross-val-score.mean \n{:.3f}'.format(score_list.mean()))

cross-val-score 
[-0.13973334  0.20290982  0.27665526  0.38187271  0.28432313]
cross-val-score.mean 
0.201


# 일별

In [8]:
df = pd.read_csv('../pre_data/일별_통합_모델링용.csv',index_col=0)
df = df.drop(columns='date')
df

price  병아리(원/수)     oil_avg  소_소비자가_int  돼지_소비자가_int  미국기준금리  한국기준금리
0      4047       400   76.703333      111396        25177    0.25    1.00
1      4047       400   77.850000      111396        25411    0.25    1.00
2      3895       400   77.566667      112019        26891    0.25    1.00
3      3895       400   77.130000      110865        26936    0.25    1.00
4      3743       400   76.530000      109225        26993    0.25    1.00
...     ...       ...         ...         ...          ...     ...     ...
2991   3166       200  108.180000       58380        19570    0.75    3.25
2992   3118       200  108.260000       58870        19830    0.75    3.25
2993   3118       300  108.470000       61700        20300    0.75    3.25
2994   3118       300  107.000000       61030        20330    0.75    3.25
2995   3118       300  105.000000       61140        20320    0.75    3.25

[2996 rows x 7 columns]

In [9]:
df = pd.read_csv('../pre_data/일별_통합_모델링용.csv',index_col=0)
df = df.drop(columns='date')

# feature, target 분리
feature = df.drop(columns='price')
target = df['price']

# train, test 분리
X_train, X_test, Y_train, Y_test = train_test_split(feature, target, test_size = 0.2, random_state = 2022)

In [6]:
RF_model = RandomForestRegressor()
RF_model.fit(feature,target)

RandomForestRegressor()

In [10]:
n_estimators = 10 

max_features = 4 

RF_reg = RandomForestRegressor(n_estimators=n_estimators, random_state=0, max_features=max_features) 

# n_estimators 는 tree의 개수를 의미 

RF_reg.fit(X_train, Y_train) # x_train['RM'].values.reshape(-1, 1) 

# 결과 예측하기 

y_pred = RF_reg.predict(X_test) # x_test['RM'].values.reshape(-1, 1) 

In [11]:
y_pred

array([3126.6       , 3000.8       , 3041.8       , 3089.6       ,
       3381.9       , 2493.7       , 2615.3       , 3093.6       ,
       3279.4       , 2676.        , 2985.8       , 2859.2       ,
       3244.9       , 3118.3       , 2800.4       , 2959.4       ,
       2889.6       , 3870.8       , 2785.2       , 3940.1       ,
       3260.2       , 3122.6       , 2821.4       , 3838.2       ,
       3311.8       , 4047.        , 3737.        , 2691.5       ,
       3096.8       , 4047.        , 3803.7       , 2915.2       ,
       3029.        , 3529.2       , 3100.8       , 3584.        ,
       3401.7       , 4133.6       , 3618.6       , 3255.3       ,
       2493.7       , 2871.        , 3331.1       , 3202.725     ,
       3636.        , 2842.9       , 2630.6       , 3062.3       ,
       2569.5       , 4194.        , 3181.        , 2621.8       ,
       3407.        , 3635.55      , 3303.4       , 2417.7       ,
       3198.1       , 4274.5       , 2630.4       , 3402.4    

In [12]:
print(RF_model.score(feature,target))

0.9868184917183987


In [14]:
score_list = cross_val_score(RF_model, feature, target)
print('cross-val-score \n{}'.format(score_list))
print('cross-val-score.mean \n{:.3f}'.format(score_list.mean()))

cross-val-score 
[ 0.10045995 -0.14098961  0.05873069 -1.63600561 -0.144764  ]
cross-val-score.mean 
-0.353
